<?php
/**
 * Point list template
 *
 * @see Goat_GetMember_Block_Member_Points
 */
/* @var $this Goat_GetMember_Block_Member_Points */
?>
<?php 
	#$_pointCollection = $this->getLoadedPointCollection();
?>
<?php if ($total = $this->getTotal()): ?>
<head>
<style>
	#point-form label {
	  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
	  font-size: 12px;
	  font-weight: 400;
	  text-align: left;
	  text-transform: uppercase;
	  min-width: 105px;
	  display: inline-block;
	  margin-right: 10px;
	}
	#point-form .field-wrapper {
	  display: inline-block;
	}

	#point-form .field-wrapper .input-text  {
	  display: inline-block;
	  width: 180px;
	}
	#point-form .button-wrapper {
	  display: inline-block;
	  vertical-align: bottom;
	}
	.cart-forms .point {
	  margin-bottom: 20px;
	  padding: 10px;
	  background-color: #f4f4f4;
	  border: 1px solid #cccccc;
	}
</style>
</head>

<form id="point-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">
    <div class="point">
        <div class="fieldset">
        	<?php echo $this->getBlockHtml('formkey')?>
            	<label ><?php echo $this->__('Member Points (R$ %s)', $total) ?></label>
                <input type="hidden" id="apply_member_point" name="apply_member_point" value="1">
                
            <div class="field-wrapper">
                <input type="text" class="input-text" id="points" name="points" value="<?php echo $this->escapeHtml($this->getPoints()) ?>">
                <div class="button-wrapper">
                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Apply')) ?>" class="button2" onclick="pointForm.submit(false)" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    <?php if($this->getPoints() > 0): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Cancel')) ?>" class="button2" onclick="pointForm.submit(true)" value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span>
                        </button>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
	var pointForm = new VarienForm('point-form');
	pointForm.submit = function (isRemove) {
	    if (isRemove) {
	        $('points').removeClassName('required-entry');
	        $('apply_member_point').value = "0";
	    } else {
	        $('points').addClassName('required-entry');
	        $('apply_member_point').value = "1";
	    }
	    return VarienForm.prototype.submit.bind(pointForm)();
	}
//]]>
</script>
<?php endif ?>